<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit80d49d3b2089f90498e44c680c02ce4b
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('PopupMaker\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \PopupMaker\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit80d49d3b2089f90498e44c680c02ce4b', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \PopupMaker\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit80d49d3b2089f90498e44c680c02ce4b', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\PopupMaker\Vendor\Composer\Autoload\ComposerStaticInit80d49d3b2089f90498e44c680c02ce4b::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
