<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'PopupMaker\\Vendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'PopupMaker\\Vendor\\CodeAtlantic\\PrerequisiteChecks\\' => array($vendorDir . '/code-atlantic/prerequisite-checks/src'),
    'PopupMaker\\Vendor\\CodeAtlantic\\Autoloader\\' => array($vendorDir . '/code-atlantic/wp-autoloader/src'),
    'PopupMaker\\' => array($baseDir . '/classes'),
);
