<?php

// autoload_static.php @generated by Composer

namespace PopupMaker\Vendor\Composer\Autoload;

class ComposerStaticInit80d49d3b2089f90498e44c680c02ce4b
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PopupMaker\\Vendor\\Psr\\Container\\' => 32,
            'PopupMaker\\Vendor\\CodeAtlantic\\PrerequisiteChecks\\' => 50,
            'PopupMaker\\Vendor\\CodeAtlantic\\Autoloader\\' => 42,
            'PopupMaker\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PopupMaker\\Vendor\\Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'PopupMaker\\Vendor\\CodeAtlantic\\PrerequisiteChecks\\' => 
        array (
            0 => __DIR__ . '/..' . '/code-atlantic/prerequisite-checks/src',
        ),
        'PopupMaker\\Vendor\\CodeAtlantic\\Autoloader\\' => 
        array (
            0 => __DIR__ . '/..' . '/code-atlantic/wp-autoloader/src',
        ),
        'PopupMaker\\' => 
        array (
            0 => __DIR__ . '/../..' . '/classes',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PopupMaker\\Vendor\\Pimple' => 
            array (
                0 => __DIR__ . '/..' . '/pimple/pimple/src',
            ),
        ),
    );

    public static $classMap = array (
        'PopupMaker\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'PopupMaker\\Base\\CallToAction' => __DIR__ . '/../..' . '/classes/Base/CallToAction.php',
        'PopupMaker\\Base\\Container' => __DIR__ . '/../..' . '/classes/Base/Container.php',
        'PopupMaker\\Base\\Controller' => __DIR__ . '/../..' . '/classes/Base/Controller.php',
        'PopupMaker\\Base\\Model\\Post' => __DIR__ . '/../..' . '/classes/Base/Model/Post.php',
        'PopupMaker\\Base\\Service' => __DIR__ . '/../..' . '/classes/Base/Service.php',
        'PopupMaker\\Base\\Service\\Repository' => __DIR__ . '/../..' . '/classes/Base/Service/Repository.php',
        'PopupMaker\\Base\\Stream' => __DIR__ . '/../..' . '/classes/Base/Stream.php',
        'PopupMaker\\Base\\Upgrade' => __DIR__ . '/../..' . '/classes/Base/Upgrade.php',
        'PopupMaker\\CallToAction\\Link' => __DIR__ . '/../..' . '/classes/CallToAction/Link.php',
        'PopupMaker\\Controllers\\Admin' => __DIR__ . '/../..' . '/classes/Controllers/Admin.php',
        'PopupMaker\\Controllers\\Admin\\CallToActions' => __DIR__ . '/../..' . '/classes/Controllers/Admin/CallToActions.php',
        'PopupMaker\\Controllers\\Admin\\Toolbar' => __DIR__ . '/../..' . '/classes/Controllers/Admin/Toolbar.php',
        'PopupMaker\\Controllers\\Admin\\WP\\PluginsPage' => __DIR__ . '/../..' . '/classes/Controllers/Admin/WP/PluginsPage.php',
        'PopupMaker\\Controllers\\Assets' => __DIR__ . '/../..' . '/classes/Controllers/Assets.php',
        'PopupMaker\\Controllers\\CallToActions' => __DIR__ . '/../..' . '/classes/Controllers/CallToActions.php',
        'PopupMaker\\Controllers\\Compatibility' => __DIR__ . '/../..' . '/classes/Controllers/Compatibility.php',
        'PopupMaker\\Controllers\\Compatibility\\Backcompat\\Filters' => __DIR__ . '/../..' . '/classes/Controllers/Compatibility/Backcompat/Filters.php',
        'PopupMaker\\Controllers\\Compatibility\\Builder\\Divi' => __DIR__ . '/../..' . '/classes/Controllers/Compatibility/Builder/Divi.php',
        'PopupMaker\\Controllers\\Compatibility\\SEO\\Yoast' => __DIR__ . '/../..' . '/classes/Controllers/Compatibility/SEO/Yoast.php',
        'PopupMaker\\Controllers\\Debug' => __DIR__ . '/../..' . '/classes/Controllers/Debug.php',
        'PopupMaker\\Controllers\\Frontend' => __DIR__ . '/../..' . '/classes/Controllers/Frontend.php',
        'PopupMaker\\Controllers\\Frontend\\Popups' => __DIR__ . '/../..' . '/classes/Controllers/Frontend/Popups.php',
        'PopupMaker\\Controllers\\PostTypes' => __DIR__ . '/../..' . '/classes/Controllers/PostTypes.php',
        'PopupMaker\\Controllers\\RestAPI' => __DIR__ . '/../..' . '/classes/Controllers/RestAPI.php',
        'PopupMaker\\Controllers\\Upgrades' => __DIR__ . '/../..' . '/classes/Controllers/Upgrades.php',
        'PopupMaker\\Controllers\\WP' => __DIR__ . '/../..' . '/classes/Controllers/WP.php',
        'PopupMaker\\Controllers\\WP\\Blocks' => __DIR__ . '/../..' . '/classes/Controllers/WP/Blocks.php',
        'PopupMaker\\Controllers\\WP\\Dashboard' => __DIR__ . '/../..' . '/classes/Controllers/WP/Dashboard.php',
        'PopupMaker\\Controllers\\WP\\I18n' => __DIR__ . '/../..' . '/classes/Controllers/WP/I18n.php',
        'PopupMaker\\Installers\\Install_Skin' => __DIR__ . '/../..' . '/classes/Installers/Install_Skin.php',
        'PopupMaker\\Installers\\PluginSilentUpgrader' => __DIR__ . '/../..' . '/classes/Installers/PluginSilentUpgrader.php',
        'PopupMaker\\Installers\\PluginSilentUpgraderSkin' => __DIR__ . '/../..' . '/classes/Installers/PluginSilentUpgraderSkin.php',
        'PopupMaker\\Integration\\QueryMonitor\\Collector\\CacheFunc' => __DIR__ . '/../..' . '/classes/Integration/QueryMonitor/Collector/CacheFunc.php',
        'PopupMaker\\Integration\\QueryMonitor\\Output\\Html\\CacheFunc' => __DIR__ . '/../..' . '/classes/Integration/QueryMonitor/Output/Html/CacheFunc.php',
        'PopupMaker\\Interfaces\\CallToAction' => __DIR__ . '/../..' . '/classes/Interfaces/CallToAction.php',
        'PopupMaker\\Interfaces\\Controller' => __DIR__ . '/../..' . '/classes/Interfaces/Controller.php',
        'PopupMaker\\Interfaces\\Service' => __DIR__ . '/../..' . '/classes/Interfaces/Service.php',
        'PopupMaker\\Interfaces\\Upgrade' => __DIR__ . '/../..' . '/classes/Interfaces/Upgrade.php',
        'PopupMaker\\Models\\CallToAction' => __DIR__ . '/../..' . '/classes/Models/CallToAction.php',
        'PopupMaker\\Plugin\\Container' => __DIR__ . '/../..' . '/classes/Plugin/Container.php',
        'PopupMaker\\Plugin\\Controller' => __DIR__ . '/../..' . '/classes/Plugin/Controller.php',
        'PopupMaker\\Plugin\\Core' => __DIR__ . '/../..' . '/classes/Plugin/Core.php',
        'PopupMaker\\Plugin\\Extension' => __DIR__ . '/../..' . '/classes/Plugin/Extension.php',
        'PopupMaker\\RestAPI\\Connect' => __DIR__ . '/../..' . '/classes/RestAPI/Connect.php',
        'PopupMaker\\RestAPI\\License' => __DIR__ . '/../..' . '/classes/RestAPI/License.php',
        'PopupMaker\\RestAPI\\ObjectSearch' => __DIR__ . '/../..' . '/classes/RestAPI/ObjectSearch.php',
        'PopupMaker\\Services\\Collector\\CallToActionTypes' => __DIR__ . '/../..' . '/classes/Services/Collector/CallToActionTypes.php',
        'PopupMaker\\Services\\Connect' => __DIR__ . '/../..' . '/classes/Services/Connect.php',
        'PopupMaker\\Services\\FormConversionTracking' => __DIR__ . '/../..' . '/classes/Services/FormConversionTracking.php',
        'PopupMaker\\Services\\Globals' => __DIR__ . '/../..' . '/classes/Services/Globals.php',
        'PopupMaker\\Services\\License' => __DIR__ . '/../..' . '/classes/Services/License.php',
        'PopupMaker\\Services\\LinkClickTracking' => __DIR__ . '/../..' . '/classes/Services/LinkClickTracking.php',
        'PopupMaker\\Services\\Logging' => __DIR__ . '/../..' . '/classes/Services/Logging.php',
        'PopupMaker\\Services\\Options' => __DIR__ . '/../..' . '/classes/Services/Options.php',
        'PopupMaker\\Services\\Repository\\CallToActions' => __DIR__ . '/../..' . '/classes/Services/Repository/CallToActions.php',
        'PopupMaker\\Services\\Repository\\Popups' => __DIR__ . '/../..' . '/classes/Services/Repository/Popups.php',
        'PopupMaker\\Services\\UpgradeStream' => __DIR__ . '/../..' . '/classes/Services/UpgradeStream.php',
        'PopupMaker\\Services\\Upgrader' => __DIR__ . '/../..' . '/classes/Services/Upgrader.php',
        'PopupMaker\\Vendor\\CodeAtlantic\\Autoloader\\Autoloader' => __DIR__ . '/..' . '/code-atlantic/wp-autoloader/src/Autoloader.php',
        'PopupMaker\\Vendor\\CodeAtlantic\\PrerequisiteChecks\\Prerequisites' => __DIR__ . '/..' . '/code-atlantic/prerequisite-checks/src/Prerequisites.php',
        'PopupMaker\\Vendor\\Pimple\\Container' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Container.php',
        'PopupMaker\\Vendor\\Pimple\\Exception\\ExpectedInvokableException' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Exception/ExpectedInvokableException.php',
        'PopupMaker\\Vendor\\Pimple\\Exception\\FrozenServiceException' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Exception/FrozenServiceException.php',
        'PopupMaker\\Vendor\\Pimple\\Exception\\InvalidServiceIdentifierException' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Exception/InvalidServiceIdentifierException.php',
        'PopupMaker\\Vendor\\Pimple\\Exception\\UnknownIdentifierException' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Exception/UnknownIdentifierException.php',
        'PopupMaker\\Vendor\\Pimple\\Psr11\\Container' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Psr11/Container.php',
        'PopupMaker\\Vendor\\Pimple\\Psr11\\ServiceLocator' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Psr11/ServiceLocator.php',
        'PopupMaker\\Vendor\\Pimple\\ServiceIterator' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/ServiceIterator.php',
        'PopupMaker\\Vendor\\Pimple\\ServiceProviderInterface' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/ServiceProviderInterface.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\Fixtures\\Invokable' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/Fixtures/Invokable.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\Fixtures\\NonInvokable' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/Fixtures/NonInvokable.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\Fixtures\\PimpleServiceProvider' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/Fixtures/PimpleServiceProvider.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\Fixtures\\Service' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/Fixtures/Service.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\PimpleServiceProviderInterfaceTest' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/PimpleServiceProviderInterfaceTest.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\PimpleTest' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/PimpleTest.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\Psr11\\ContainerTest' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/Psr11/ContainerTest.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\Psr11\\ServiceLocatorTest' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/Psr11/ServiceLocatorTest.php',
        'PopupMaker\\Vendor\\Pimple\\Tests\\ServiceIteratorTest' => __DIR__ . '/..' . '/pimple/pimple/src/Pimple/Tests/ServiceIteratorTest.php',
        'PopupMaker\\Vendor\\Psr\\Container\\ContainerExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerExceptionInterface.php',
        'PopupMaker\\Vendor\\Psr\\Container\\ContainerInterface' => __DIR__ . '/..' . '/psr/container/src/ContainerInterface.php',
        'PopupMaker\\Vendor\\Psr\\Container\\NotFoundExceptionInterface' => __DIR__ . '/..' . '/psr/container/src/NotFoundExceptionInterface.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit80d49d3b2089f90498e44c680c02ce4b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit80d49d3b2089f90498e44c680c02ce4b::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit80d49d3b2089f90498e44c680c02ce4b::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit80d49d3b2089f90498e44c680c02ce4b::$classMap;

        }, null, ClassLoader::class);
    }
}
